---
version: "3.8"


services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    network_mode: host
    volumes:
      - type: bind
        source: ${APPS_DATA}/portainer
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: always
